package enums;

public enum TransactionStatus {
	INSERTADA_CORRECTAMENTE,
	ERROR_EN_PARAMETROS_RECIBIDOS,
	ERROR_INTERNO_ANTES_DE_ENCOLARSE,
	INTERRUPCION_AL_PROCESAR,
	FINALIZADA_OK,
	FINALIZADA_NOK,
	INICIADA
}
