package enums;

public enum TransactionStatus {
	FINALIZA_ENCOLAMIENTO,
	ERROR_EN_PARAMETROS_RECIBIDOS,
	ERROR_INTERNO_ANTES_DE_ENCOLARSE,
	INTERRUPCION_AL_PROCESAR,
	FINALIZADA_OK,
	FINALIZADA_NOK,
	INICIA_PROCESAMIENTO, 
	INICIA_ENCOLAMIENTO
}
